USE_OHMYZSH=false
USE_ZPLUG=true

if $USE_OHMYZSH; then
  export ZSH="$HOME/.oh-my-zsh"

  ZSH_THEME="robbyrussell"
  #ZSH_THEME="random"
  #ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

  #COMPLETION_WAITING_DOTS="true"

  # Uncomment the following line if you want to disable marking untracked files
  # under VCS as dirty. This makes repository status check for large repositories
  # much, much faster.
  #DISABLE_UNTRACKED_FILES_DIRTY="true"

  plugins=(
    git
  )

  source $ZSH/oh-my-zsh.sh
fi

if $USE_ZPLUG; then
  export ZPLUG_HOME="$HOME/.zplug"

  if [ ! -e "$ZPLUG_HOME" ]; then
    printf "Installing zplug..."
    curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
  fi

  source "$ZPLUG_HOME/init.zsh"

  zplug "zsh-users/zsh-syntax-highlighting"

  # Oh My Zsh
  zplug "plugins/command-not-found", from:oh-my-zsh

  # Prompt
  zplug "denysdovhan/spaceship-prompt", use:spaceship.zsh, from:github, as:theme
  #zplug "themes/robbyrussell", from:oh-my-zsh, as:theme
  #zplug "mafredri/zsh-async", from:github
  #zplug "sindresorhus/pure", use:pure.zsh, from:github, on:zsh-async, as:theme

  # Install plugins if there are plugins that have not been installed
  if ! zplug check; then
    printf "Install? [y/N]: "
    if read -q; then
      echo; zplug install
    fi
  fi

  zplug load
fi

# User configuration

export PATH="$HOME/.cargo/bin:$PATH"
# export MANPATH="/usr/local/man:$MANPATH"
export DOT="$HOME/.dot"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
else
  export EDITOR='nvim'
fi

# Preferred keybindings
# Emacs
bindkey -e
# Vim
#bindkey -v

# Enable Ctrl-x-e to edit command line
autoload -U edit-command-line
# Emacs style
zle -N edit-command-line
bindkey '^xe' edit-command-line
bindkey '^x^e' edit-command-line
# Vi style:
# zle -N edit-command-line
# bindkey -M vicmd v edit-command-line

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
alias zshconfig="$EDITOR ~/.zshrc"
alias ohmyzsh="$EDITOR ~/.oh-my-zsh"
alias vimconfig="$EDITOR ~/.config/nvim/plug.vim"
alias ls="ls --color=auto"
alias bpython=bpython3

export MANPAGER="nvim -c 'set ft=man' -"

# tmux italics/true color
tic -x "$DOT/aux/xterm-256color-italic.terminfo"
tic -x "$DOT/aux/tmux-256color.terminfo"
export TERM=xterm-256color-italic
# Prevent it from breaking ssh
alias ssh='TERM=xterm-256color ssh'

# Completion
if command -v docker-compose &>/dev/null; then
  fpath=(~/.zsh/completion $fpath)
  autoload -Uz compinit && compinit -i
fi
if command -v pipenv &>/dev/null; then
  eval "$(pipenv --completion)"
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# ripgrep
if command -v rg &>/dev/null; then
  export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*" 2>/dev/null'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
elif [ ! -e ~/.fzf-no-ripgrep ]; then
  echo "FZF can use ripgrep for greater speed."
  echo "To install ripgrep, run the following commands:"
  echo -e "\tsudo apt install cargo"
  echo -e "\tcargo install ripgrep"
  echo
  echo "If you want to disable this message, run the following command:"
  echo -e "\ttouch ~/.fzf-no-ripgrep"
fi
