#!/usr/bin/env bash
# Make links to every configuration

cd ~/.dot

for line in "$(cat map)"; do
    # TODO
    src=$(echo "$line" | cut -d\t -f1)
    dest=$(echo "$line" | cut -d\t -f2)
    echo $src  | xxd
    echo $dest | xxd
done
